[config]
host = "127.0.0.1"
user = "jonas"
password = "Artemis34!!"
port = 22

[group.B]
host = "127.0.0.1"
user = "jonas"
password = "artemisJP!!"
port = 22


[task.B]
cmd.builtin.copy = { file = "~/Documents/ProjektdokumentationFachinformatikerAnwendungsentwicklung2021AlinaAhrens.pdf", location = "~/Downloads/" }

name = "test"
cmd.builtin.shell = { name = "bash", args = ["-c", "ls"] }
# [task.A]
# command = "ls"
#
#
# [task.C]
# #command = "ls"
