[package]
name = "rsrem"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = "0.8.4"
crossbeam-channel = "0.5.11"
curl = "0.4.46"
log = "0.4.20"
openssl = { version = "0.10.64", features = ["v110"] }
regex = "1.10.3"
russh = "0.42.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
smol = "2.0.0"
ssh2 = { version = "0.9.4", features = ["vendored-openssl"] }
toml = "0.8.10"
